name: stream_core_flutter_workspace

environment:
  sdk: ^3.10.0

dev_dependencies:
  code_builder: ^4.10.1
  icon_font_generator: ^4.1.0
  melos: ^6.2.0
  path: ^1.9.0
  recase: ^4.1.0
  yaml: ^3.1.3
