name: design_system_gallery
description: "Stream Design System Gallery - A comprehensive widgetbook for exploring and customizing Stream components."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  device_frame_plus: ^1.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.5+1
  stream_core_flutter:
    path: ../../packages/stream_core_flutter
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.20.1

flutter:
  uses-material-design: true