name: stream_core_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  stream_core: ^0.4.0
  theme_extensions_builder_annotation: ^7.1.0

dev_dependencies:
  alchemist: ^0.13.0
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  theme_extensions_builder: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/file_type/

  fonts:
    - family: Stream Icons
      fonts:
        - asset: packages/stream_core_flutter/fonts/stream_icons_font.otf

