name: Publish Design System Gallery

on:
  push:
    branches:
      - main-design-system
  workflow_dispatch:

env:
  FLUTTER_CHANNEL: stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_gallery:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: config git
        run: |
          git config --global user.email "$(git log --format='%ae' HEAD^!)"
          git config --global user.name "$(git log --format='%an' HEAD^!)"
          git fetch origin gh-pages:gh-pages

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build and Deploy
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /stream-core-flutter/
          workingDir: apps/design_system_gallery
